server:
  port: 8083
  servlet:
    context-path: "/product"

spring:
  application:
    name: product-service
  datasource:
    url: ${DBMS_CONNECTION}
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver


  data:
    redis:
      host: ${REDIS_HOST:redis-12731.c252.ap-southeast-1-1.ec2.redns.redis-cloud.com}
      port: ${REDIS_PORT:12731}
      password: ${REDIS_PASSWORD}
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 5s

cloudinary:
  cloud_name: dis2ybh5i
  api_key: ${CLOUDINARY_KEY}
  api_secret: ${CLOUDINARY_SECRET}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true