server:
  port: 8080

app:
  api-prefix: /gateway/v1

spring:
  application.name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2
            - RewritePath=/identity/(?<remaining>.*), /identity/v1/${remaining}

